version: 0.2

env:
  variables:
    ECR_MAIN_URI: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    ECR_IMAGE_URI: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:latest"

phases:
  pre_build:
    commands:
      - echo "Login to DockerHub..."
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin

      - echo "Login to ECR..."
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}

      - echo "ECR Image URI ${ECR_IMAGE_URI}"

  build:
    commands:
      - echo "Building and pushing Docker image with BuildKit..."
      - DOCKER_BUILDKIT=1 docker build --push -t ${ECR_IMAGE_URI} .

  post_build:
    commands:
      - echo "Creating imagedefinitions.json..."
      - echo "[{\"name\":\"tictactoe-container\",\"imageUri\":\"${ECR_IMAGE_URI}\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
